server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 8100

spring:

  # RabbitMQ ??
  rabbitmq:
    host: 52.79.143.215
    port: 5672
    username: guest
    password: guest

  # H2 ??
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 1234
#  sql:
#    init:
#      mode: always

  # JPA ??
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true # Hibernate 초기화 이후 Init Data 동작

# Logging
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"
  level:
    org:
      hibernate: info