server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 8100

spring:

  # RabbitMQ ??
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # H2 ??
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 1234

  # JPA ??
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org:
      hibernate: info